version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: ./entry-and-populate-db.sh python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend-node-modules:/frontend/node_modules
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com" # You can change this
      PGADMIN_DEFAULT_PASSWORD: "adminpassword"  # And this too
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin    
volumes:
  postgres_data:
  frontend-node-modules:
  pgadmin_data:

